title: Pysselfika!
description: > # this means to ignore newlines until "show_excerpts:"
  Pysselsfikas hem på nätet. Ett tillfälle att umgås, pyssla och ha det gött.

markdown: kramdown
remote_theme: pages-themes/leap-day@v0.2.0

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-remote-theme